install:
  - choco install openmodelica --version=1.14.1
  - set PATH=%PATH%;C:\Program Files\OpenModelica1.14.1-64bit\bin
  - omc --version

build_script:
  - mkdir %TEMP%\zzzz
  - xcopy deviation_c.mo %TEMP%\zzzz
  - xcopy CMakeLists.txt %TEMP%\zzzz
  - xcopy wrapper.c %TEMP%\zzzz
  - xcopy mo2fmu.bat %TEMP%\zzzz
  - cd %TEMP%\zzzz
  - cmake -DCMAKE_GENERATOR_PLATFORM=x64 .
  - cmake --build . --config Release
  #- copy cwrapper.lib libcwrapper.lib
  - mo2fmu deviation_c
  - dir /p
  - dir /p C:\projects\openmodelica-fmu-export-win\

  #- dir /p C:\projects\openmodelica-fmu-export-win\deviation_c.fmutmp
  #- dir /p C:\projects\openmodelica-fmu-export-win\deviation_c.fmutmp\sources
  #- dir /p C:\projects\openmodelica-fmu-export-win\deviation_c.fmutmp\resources
  #- type C:\projects\openmodelica-fmu-export-win\deviation_c.fmutmp\resources\static.log
